moneyadviceservice/publify

app/assets/stylesheets/layouts/_article.scss

- added ol and ul to list of items to restrict to 550px on
'desktop' viewport widths

Max width of a list within an article

---

app/views/articles/_meta.html.erb

The category link is hard coded at the moment, and not required for first release so this removes it.

Remove category link on article pages

---

app/controllers/admin/content_controller.rb
spec/controllers/admin/content_controller_spec.rb

Remain on the article editing page after saving

---

app/assets/stylesheets/components/comments/_comments.scss
app/assets/stylesheets/layouts/_page.scss
app/views/articles/_comment_form.html.erb
app/views/articles/read.html.erb
app/views/articles/view_page.html.erb
config/locales/en.yml

This deals with the following tickets:
#4554 Agree to rules of engagement
https://moneyadviceservice.tpondemand.com/entity/4554
#4186 Rules of engagement around commenting https://moneyadviceservice.tpondemand.com/entity/4186
- Adding text above and near the post button which links to the
commenting policy page
- Added text to the en language file
- Applied basic styling to a non-article page
- /pages/commenting-policy will need to be created in the
admin for the link to work

Commenting policy links

---

app/views/admin/dashboard/_welcome.html.erb
spec/controllers/admin/dashboard_controller_spec.rb

`Admin::FeedbackController#index` expects a filter to be specified in the [`only` param](https://github.com/moneyadviceservice/publify/blob/d8df2bf923a2faf5fab1e18495573fffb926c2a3/app/controllers/admin/feedback_controller.rb#L8).
__NOTE:__ the `unconfirmed` scope only [exists on Feedback](https://github.com/moneyadviceservice/publify/blob/d8df2bf923a2faf5fab1e18495573fffb926c2a3/app/models/feedback.rb#L28) and [not Comment](https://github.com/moneyadviceservice/publify/blob/d8df2bf923a2faf5fab1e18495573fffb926c2a3/app/models/comment.rb#L16) so I've used the `unapproved` scope instead.
I'll see about getting this into upstream as well.

Use correct query string params in dashboard links

---

Gemfile
Gemfile.lock
app/controllers/articles_controller.rb
app/views/articles/index_json_feed.json.jbuilder
app/views/shared/_json_item_article.json.jbuilder
config/routes.rb
spec/controllers/articles_controller_spec.rb
spec/spec_helper.rb
spec/views/articles/index_json_feed_spec.rb

Accessible via `/articles.json`
We're using this to provide a "Latest links" section in frontend. We're
using JSON here for reasons of consistency with other MAS projects, e.g.
frontend and contento. Tests are more or less copied and tweaked from
the tests for the RSS feed.
This doesn't contain as much information as /articles.rss, because that
would require a bit more work/testing and it's not required for now.

Provide a minimal JSON feed for the latest articles.

---

app/assets/stylesheets/administration_structure.css.scss
app/controllers/admin/content_controller.rb
app/models/article.rb
app/models/article/factory.rb
app/models/article/states.rb
app/models/content.rb
app/views/admin/content/_article_list.html.erb
app/views/admin/content/_form.html.erb
app/views/admin/content/index.html.erb
config/locales/en.yml
spec/controllers/admin/content_controller_spec.rb
spec/models/article/factory_spec.rb

- rearrange article editing layout to make better use of space
- reintroduce standard layout, more useful that way and also side steps cancel button confusion
- simpler workflow - draft > published > withdraw > reinstate
- do away with modal publishing window, it simply wasn't properly thought through and the flow didn't work
- redo saving buttons to deal with broken workflow and make more intuitive
- more descriptive flash messages to communicate exactly what's happened on a save
- remove no longer used autosave functionality and with that other now pointless complexity
- some improvements to the article list - clearer identifying of non published article states, better filtering

Reworking of article editing

---

app/views/articles/_comment_form.html.erb

Chrome seems to no longer respect `autocomplete="off"` on input fields, and rather only works when set on the whole form tag.
However setting it to a string other than 'off' fixes it.

Disable autocomplete on comments

---

app/controllers/admin/content_controller.rb
app/views/admin/content/_form.html.erb

So, this is a bit of a bodge but I've not been able to nail the root cause of this issue.
Basically what's happening is that when you try to use the standard carrierwave functionality to remove an image, it attempts the removal of the images from the cdn twice.  It seems to be something within the callback chain as you're able to call ``remove_hero_image!`` and remove the image, but then when you try to save the record to update the column content, it tries to do the removal again.
So what this does is simply perform the image removal then uses ``update_column`` to perform the update without triggering any callbacks.
It's not pretty but it does the job.

Alternative approach to removing hero and teaser images

---

app/views/articles/_article.html.erb

Based on Feedback from Jade, she requested that we removed the speech bubble where there are no comments

hide zero comments on tiles

---

app/views/articles/_article.html.erb
config/locales/en.yml

- now reads out '1 comment' or '2 comments' etc
when screenreader reads out homepage tiles

Added hidden text for comments

---

app/views/shared/_header.html.erb

- only have link around blog title when you're not on homepage
- added off screen text to indicate its a link to the homepage

blog title in header

---

app/assets/stylesheets/components/skip_to_link/_skip_to_link.scss

After merging in the skip to content link, the main tag on each page when clicked on can result in a blue outline

stop main tag from showing blue focus box

---

app/assets/stylesheets/_settings.scss
app/assets/stylesheets/components/tiles/_article_tile.scss
app/views/articles/_article.html.erb
app/views/shared/_also_like.html.erb

- colour pattern of tiles now changes between
(0 to $mq-l) and ( >= $mq-l) to ensure that
there are no repeating patterns of colour
in a row or below
- removed class names for tiles as no longer
required (one, two, mas etc) - using
nth-child selectors now

altered way tile colours are output

---

app/assets/stylesheets/layouts/_campaigns.scss
app/controllers/admin/campaigns_controller.rb
app/models/campaign.rb
app/views/admin/campaigns/_form.html.erb
app/views/shared/_campaigns.html.erb
db/migrate/20150123105303_add_full_bleed_to_campaigns.rb
db/schema.rb
spec/factories.rb
spec/features/campaign_pages_spec.rb
spec/models/campaign_spec.rb
spec/support/pages/new_campaigns_page.rb

- added full_bleed column to campaign table
- enabled checkbox in admin to choose between
full bleed and non-full bleed (for illustrations)
- altered template and css to enable the toggle
between the two options

adding option to make homepage image full bleed

---

app/assets/stylesheets/bootstrap.css.scss
app/assets/stylesheets/components/article_body/_collapsible.scss
app/assets/stylesheets/components/article_body/_inline_callout.scss
app/views/admin/content/_form.html.erb
app/views/shared/_collapsible.html.erb
app/views/styleguide/show.html.erb
lib/publify_textfilter_answer_reveal.rb

- non-js shows question and answer with no trigger
- trigger uses dough collapse to reveal answer
- transitions on plus icon to convert to minus when open
- overridden styles for call out to MAS green if URL is a MAS one

adding interactivity to answer reveal

---

app/assets/stylesheets/components/tiles/_article_tile.scss

Example page where the issue is:
https://blog.moneyadviceservice.org.uk/tag/savings

fixing issue where yellow tile was appearing on tag pages

---

app/assets/stylesheets/layouts/_header.scss
app/assets/stylesheets/layouts/_tiles.scss
app/views/articles/index.html.erb
app/views/tags/show.html.erb
config/locales/en.yml

- adjusting layout of l-tiles so that tag title can sit
flush underneath header
- adjusted position of header title slightly to look
better at 720px and at other viewport widths so that
it sits centrally with the tag title
- ensure that homepage is unaffected by changes above

Adding in a title for the tag page

---

app/assets/stylesheets/_settings.scss
app/assets/stylesheets/components/tiles/_article_tile.scss
app/assets/stylesheets/lib/_colors.scss

- to ensure that tag page blue header isn't sit
directly above a blue tile on mobile
- changed blue of tile to same blue in header of blog
based on request from Jade

adjusted pattern of colors for tiles

---

app/views/articles/search.html.erb

Adds missing `action` attribute.
When trying to search for a new term on page 2 onwards of the search results page, the form submits to itself and not via the /search route and thus doesn't show the new search results.
@Guntrisoft @moneyadviceservice/team-bee 
id:6265

Fix search URL on paginated search pages

---

app/assets/stylesheets/components/results_list/_results_list.scss

After discussions with Jade it was decided the pagination should be on the left.

Left align pagination

---

app/controllers/application_controller.rb
app/controllers/news_controller.rb
app/helpers/tag_helper.rb
app/models/article.rb
app/views/shared/_footer.html.erb
app/views/tags/show.html.erb
config/locales/en.yml
config/routes.rb
spec/controllers/news_controller_spec.rb
spec/models/article_spec.rb
spec/requests/slash_news_spec.rb
spec/views/layouts/default_spec.rb

- Articles tagged as `News` are available at `/news/PERMALINK`
- fix api for popular articles
- `/news` will render the same as `/tag/news`. a redirect was not acceptable

News section

---

app/assets/stylesheets/layouts/_footer.scss
app/views/shared/_footer.html.erb

- added a visually hidden headline to give context to the
new text layout for signup

id:6461 comment: Blog newsletter sign-up CTA copy change

---

config/unicorn.rb

We have 5 dynos currently with 2 unicorns each. however this is still going into swap as evident on the dashboard
this will reduce to 1 unicorn per box bringing down the total app instances from 10 to 5

reduce unicorns per server

---

app/assets/stylesheets/components/mas_video/_all.scss
app/assets/stylesheets/components/mas_video/_mas_video.scss
app/views/admin/content/_form.html.erb

Adding additional CSS to handle responsive video, The classname's are very specific to MAS
`.mas-video-container` and `.mas-video`
Specificity is required as these are also used in webfeeds so a class of .video may not have been suitable as there is a good chance that a partner hosting our content will also have CSS for a class of this name.
As new containers have been added, a youtube snippet option has also been added to the editor as content creators usually paste the embed code straight into the source of the editor, they will now need to copy the snippet into the editor and then paste their embed code within it:
| Button | Snippet |
|----------|------------|
|<img width="406" alt="screen shot 2016-02-12 at 14 32 03" src="https://cloud.githubusercontent.com/assets/13165846/13009670/a9d …

[DEV APPROVED] #7022 Responsive Videos - Blog

---

build.sh
pre-build.sh

There was a lot of Go problems when precompiling the assets. The problem that the build and test was running in parallel and they were affecting each other.

Move the precompile and bundle to pre-build

---

app/models/ckeditor/application_controller.rb

The [application controller](https://github.com/galetahub/ckeditor/blob/d0bc44a6fc9fa67d4b007877688f89e5a0cbf79f/app/controllers/ckeditor/application_controller.rb#L19) at revision [d0bc44a6](https://github.com/galetahub/ckeditor/tree/d0bc44a6fc9fa67d4b007877688f89e5a0cbf79f) of the CKEDITOR that we [currently use](https://github.com/moneyadviceservice/publify/blob/e4ea8bc134c0deaa56feea356651364f489de23f/Gemfile.lock#L3) prepends the `relative_url_root` in its response whether the uploaded asset's URL is relative or not.
This is OK locally but uploading an image to the CDN results in:
This terrible monkey patch is just a copy of the original controller code with the addition of a private method that checks if the asset's URL is relative or not.
Later versions of CKEDITOR have been …

Patch CKEDITOR application controller to return relative or absolute URL

---

Gemfile
Gemfile.lock
app/controllers/articles_controller.rb
app/views/articles/index.json.jbuilder
app/views/shared/_json_item_article.json.jbuilder
config/routes.rb

The functionality has been accidentally removed for the blog to produce a JSON feed for the CMS to pick up and send to the frontend for the 'From our blog' section on an article page.
This PR created this functionality again, There is an associated PR for the CMS which addresses the URL change from:
```
blog.moneyadviceservice.org.uk
```
To
```
www.moneyadviceservice.org.uk/blog
```
Related CMS PR
[BUG: Updating Publify API call for new blog url](https://github.com/moneyadviceservice/cms/pull/331)

[DEV APPROVED] 7421 - BUG: blog JSON feed for 'From our blog' section

---

build.sh
etc/after_install
etc/service-script

This has been hard to do with the external 'create-rails-rpm' script we
have, so we've added RPM generation to the build.sh script here.
The whole complication of having the external tool `create-rails-rpm` which is in a repo `rpm_builder` which is a sub-module pulled into `scripts` it ... a bit complicated. So this PR is testing out the idea of moving this logic, along with the `after-install` and service start/stop scripts into the application repo. This gives us finer granularity control when it comes to controlling these things, balanced out with more work if we want to fundamentally change how we build RPMs (we'll have to make changes to multiple RPM build scripts).
If this change looks good and once we've proved it works, we should move forward with changing `frontend` and `cms` to …

Ensure public/cache has the right ownership in RPM.

---

app/views/shared/_page_header.html.erb

Presumed to have been broken during the blog migration, posting to Facebook via HootSuite no longer pulls in the expected article metadata.
Using the Facebook Open Graph debugger, you can see the issue lies with the `og:url` metatag.
Additionally, I compared an article's metatags from now to the past (via archive.org).
Before:
```
<meta property="og:site_name" content="Your Money Advice" />
<meta property="og:title" content="How much do you spend on your household bills?" />
<meta name="og:description" content="We spend nearly £200 on our main household bills each month. Can you cut your bills?" />
<meta property="og:url" content="http://blog.moneyadviceservice.org.uk/how-much-do-you-spend-on-your-household-bills" />
<meta property="og:image" …
```

Open Graph and Twitter url metatags should be full urls with host

---

app/assets/stylesheets/_settings.scss
app/assets/stylesheets/components/also_like/_also_like.scss
app/assets/stylesheets/components/tiles/_article_tile.scss
app/assets/stylesheets/layouts/_tiles.scss
app/views/articles/read.html.erb

As a result of an A/B test the requirement is to swap the comment block and the related articles, please see below for before and after screenshots:
|Before|
|-------|
|![blog--before](https://cloud.githubusercontent.com/assets/13165846/16945864/d7e9423c-4d9e-11e6-8922-43edc74a4121.png)|
|After|
|-----|
|![blog--after](https://cloud.githubusercontent.com/assets/13165846/16945872/e1879618-4d9e-11e6-9b37-6143b1aae090.png)|

[DEV APPROVED] 7467 - Swapping Comments and Related articles

---

app/views/shared/_footer.html.erb

For ease of accessibility, the social sharing icon SVG's need to have descriptive titles

[DEV APPROVED] 7459 - Adding descriptive titles to social sharing SVG's

---

build.sh
pre-build.sh
test.sh

This was in pre-build.sh, with the results being tarred up for Go to
grab it and send it to the test and build jobs. However, it doesn't
appear to be needed by test so we should be able to get by with only
precompiling in the build job.

[DEV APPROVED] Move asset precompile to build.sh

---

Gemfile
Gemfile.lock
app/assets/javascripts/require_config.js.erb
app/assets/stylesheets/_enhanced.css.scss
app/assets/stylesheets/layouts/_footer.scss
app/assets/stylesheets/layouts/_header.scss
app/views/articles/search.html.erb
bower.json.erb
spec/models/note_spec.rb
spec/models/post_type_spec.rb
spec/models/redirect_spec.rb
spec/models/tag_spec.rb

**The Problem**
When a user performed a search on the blog, the focus would be in the usual place on the results page, so they would have to tab all the way down the the results.
**The Solution**
|1) Force focus to the 1st result if there is a result|
|----------|
|<img width="500" alt="article found" src="https://cloud.githubusercontent.com/assets/13165846/18122029/6ad8fd9e-6f5f-11e6-9d0a-a24657afb770.png">|
|2) If no result is found, the focus is on the search bar|
|----------|
|<img width="500" alt="no articles found" src="https://cloud.githubusercontent.com/assets/13165846/18122053/858c2df0-6f5f-11e6-85d6-33dd2e804a13.png">|
|3)If a user goes directly to the search page, the focus is in the normal place at the top with the accessibility links|
|----------|
|<img width="500" …

[DEV APPROVED] 7558 - Blog: Post search focus should remain on the search box

---

Gemfile
Gemfile.lock
app/assets/javascripts/require_config.js.erb
app/assets/stylesheets/_enhanced.css.scss
app/assets/stylesheets/layouts/_footer.scss
app/assets/stylesheets/layouts/_header.scss
app/views/articles/search.html.erb
bower.json.erb
spec/models/note_spec.rb
spec/models/post_type_spec.rb
spec/models/redirect_spec.rb
spec/models/tag_spec.rb

**The Problem**
When a user performed a search on the blog, the focus would be in the usual place on the results page, so they would have to tab all the way down the the results.
**The Solution**
|1) Force focus to the 1st result if there is a result|
|----------|
|<img width="500" alt="article found" src="https://cloud.githubusercontent.com/assets/13165846/18122029/6ad8fd9e-6f5f-11e6-9d0a-a24657afb770.png">|
|2) If no result is found, the focus is on the search bar|
|----------|
|<img width="500" alt="no articles found" src="https://cloud.githubusercontent.com/assets/13165846/18122053/858c2df0-6f5f-11e6-85d6-33dd2e804a13.png">|
|3)If a user goes directly to the search page, the focus is in the normal place at the top with the accessibility links|
|----------|
|<img width="500" …

[DEV APPROVED] Adding search focus component

---

Gemfile
Gemfile.lock

This PR changes the reference to Dough in the Gemfile from
```
gem 'dough-ruby', '~> 5.0', git: 'https://github.com/moneyadviceservice/dough.git', require: 'dough'
```
to
```
gem 'dough-ruby', '~> 5.0', require: 'dough'
```
So that it does not rely on the github branch, and instead uses the Gem.
It is my understanding that ``require: 'dough'`` is needed as the gem name differs from dependency name (eg in bower.json.erb ``"dough": "<%= gem_path('dough-ruby') %>"``).

[DEV APPROVED] 7612 - Removing ref to dough git branch

---

app/views/shared/_footer.html.erb

An illogical heading structure was encountered on the search page, where headings jumped form an h1 to an h3. This can cause confusion for screen reader users. Ensuring that an h2 is present between the h1 and h3 will benefit this user group.
The solution for this is to add a hidden H2 to the footer section ``<h2 class="visually-hidden">Footer links</h2>``. This identifies the links in the footer as a section containing links and ensures that the H3's in the footer follow a H2.

[DEV APPROVED] Adding H2 to footer

---

app/assets/stylesheets/_settings.scss
app/assets/stylesheets/components/tiles/_article_tile.scss
app/assets/stylesheets/lib/_colors.scss

**Accessibility Audit page 94** 
The 'You might also like...' links -  the box that links to core site is green on white - at too low a contrast ratio to be accessible.
This PR darkens the green background colour to the MAS green/White scheme to improve contrast.
| Current |
|---------|
|<img width="1193" alt="screen shot 2016-09-27 at 11 23 33" src="https://cloud.githubusercontent.com/assets/13165846/18869586/de2a1332-84a4-11e6-9fab-4556f0f340e2.png">|
| New |
|------|
|<img width="1214" alt="screen shot 2016-09-27 at 11 21 22" src="https://cloud.githubusercontent.com/assets/13165846/18869546/afa4b9c2-84a4-11e6-99ee-0ff8a54b3549.png">|

[DEV APPROVED] 7637 - A11Y: Change colours on the blog recirculation link

---

app/views/articles/_comment_form.html.erb
app/views/articles/read.html.erb

The Blog comments module links to the blog comment policy twice (once above and once below the comment)
Both of these currently link to: https://www.moneyadviceservice.org.uk/pages/commenting-policy  - which does not exist
They should link, instead to: https://www.moneyadviceservice.org.uk/blog/pages/commenting-policy
Presumably this bug has snuck in since the blog migration
This PR fixes this problem

[DEV APPROVED] 7644 - Updating blog commenting policy links

---

app/views/articles/_article.html.erb
app/views/shared/_also_like.html.erb
app/views/shared/_footer.html.erb

This PR removes the title attribute from links to blog posts in four areas: 
* Home page:
* the links in tiles
* under "What's popular"
* under "Latest posts"
* post page: 
* under "You might also like"

[DEV APPROVED] TP: 7640, Comment: Removes title attribute from blog post links

---

app/assets/stylesheets/_enhanced.css.scss
app/assets/stylesheets/_settings.scss
app/assets/stylesheets/base/_links.scss
app/assets/stylesheets/components/article_body/_inline_callout.scss
app/assets/stylesheets/components/campaigns-link/campaigns-link.scss
app/assets/stylesheets/components/comments_count/_settings.scss
app/assets/stylesheets/components/tiles/_article_tile.scss
app/assets/stylesheets/layouts/_footer.scss
app/views/articles/_comment.html.erb

This PR 
- updates the colour of links to the darker blue as used on the core site
- underlines the links (removed for hover state)
**Current (Media centre shows hover state):** 
**Updated (Media centre shows hover state):** 
To do this it removes the publify-specific variable $link-color and uses the variable $color-link-default from Yeast instead in all places that variable has been used (most notably for the hover state of the social sharing icons).

[DEV APPROVED] TP: 7638, Comment: Updates link styles on blog for better accessibility

---

app/views/archives/kaminari/_paginator.html.erb
app/views/articles/index.html.erb
app/views/shared/_campaign_link_article.html.erb
app/views/shared/_campaign_link_masays.html.erb
app/views/shared/_footer.html.erb
app/views/tags/kaminari/_next_page.html.erb

This PR removes SVG's from the tab order, ``tabindex="-1"`` was mentioned in the ticket for this task but had no effect in IE11, ``focusable="false"`` worked in all cases.
**Related PR's**
Dough
https://github.com/moneyadviceservice/dough/pull/276
Frontend
https://github.com/moneyadviceservice/frontend/pull/1566

[DEV APPROVED] 7673 - Adding focusable false to SVGs

---

app/views/admin/contents/_form.html.erb

Publify allows for the insertion of iframes, which the blog team uses to embed Infogram infographics, quizzes and surveys into their content. As the Accessibility report (p33-34) highlights, iframes need title attributes in order to pass AA Accessibility.
However the blog does not have anything which would remove markup, what goes into the source will be rendered onto the page as it is.
The solution is to ensure that the content team know to include a title tag to iframes pasted in from other sources (Which Ed will do).  For cost calculators they embed through publify, the prompt has been changed to request that an iframe title is added when they use the code snippet:

[DEV APPROVED] 7679 - Adding TITLE prompt to cost calculator iframe embed

---

app/views/admin/contents/_form.html.erb

There has been a change somewhere down the line either to our code or a browser update that meant that a content editor on the blog was unable to highlight the code snippets for cost calculator etc...
This fixes the problem by adding a readonly=true attribute to the textareas which contain the snippets:
The text areas can now be selected and no edited by the content editors.
Tested across the following browsers:
Firefox
Chrome
Safari
IE8
IE9
IE10
IE11
MSEDGE

[DEV APPROVED] 7731 - Blog: Copying snippet code struggle

---

Gemfile
Gemfile.lock
app/assets/stylesheets/amp_styles.css.scss
app/controllers/amp_articles_controller.rb
app/models/amp_processor.rb
app/views/admin/contents/_form.html.erb
app/views/articles/amp/show.html.erb
app/views/shared/_page_header.html.erb
app/views/shared/_svg_sprite.html.erb
config/locales/en.yml
config/routes.rb
db/migrate/20161129152334_add_supports_amp_to_content.rb
db/schema.rb
spec/controllers/amp_articles_controller_spec.rb
spec/models/amp_processor_spec.rb

This PR is very similar to https://github.com/moneyadviceservice/frontend/pull/1577.  It sets up a separate show view for blog posts so they can be viewed and comply to Google AMP.
- We create an `/amp` sub-route for articles that returns a AMP compliant view. 
- We have created a separate Amp Articles controller 
- This Subclasses `ActionController::Base` rather than `ApplicationController` because we need to limit everything that gets pulled into the view.
- We created a very basic view that only has AMP compliant HTML as well as various other AMP requirements (i.e. importing the AMP JS lib)
- We created a `amp_styles.scss` file.  This includes very little styles because AMP requires that styling is kept bellow 50Kb
- We link AMP Article views with Articles views and vice versa with …

[DEV APPROVED]Add support for Google AMP.

---

Gemfile.lock
app/controllers/sitemaps_controller.rb
spec/controllers/sitemaps_controller_spec.rb
spec/views/sitemaps/show_xml_builder_spec.rb

This PR fixes this [card](https://moneyadviceservice.tpondemand.com/entity/7921). 
**Pages** and **Tags** now are excluded from showing up in the _Sitemap_ XML document. Apart form the fact that they were throwing up blanks they have no SEO benefit. Pages, for instance, do not contain consumer focused article. See an example of a page [here](https://www.moneyadviceservice.org.uk/blog/pages/commenting-policy).
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/moneyadviceservice/publify/220)

[DEV APPROVED] 7921 sitemap error

---

app/views/articles/read.html.erb
app/views/author/show.html.erb
db/schema.rb
spec/controllers/amp_articles_controller_spec.rb
spec/models/amp_processor_spec.rb

atom and RSS feeds on author and article pages were auto generating erroneous links into the header generating 404 errors when followed by crawlers

[DEV APPROVED]Fix atom and rss feeds

---

app/controllers/text_controller.rb
app/models/blog.rb
app/views/admin/settings/seo.html.erb
app/views/shared/_page_header.html.erb
config/locales/en.yml
config/routes.rb
spec/controllers/text_controller_spec.rb
spec/models/blog_spec.rb

The Humans.txt file is causing tons of errors on the blog.  This PR removes the humans.txt file and the option from the admin interface (to prevent confusion for the content editors).
Tests have also been removed relating to this file.

[DEV APPROVED] 8276 - Removes humans.txt from Blog

---

app/controllers/amp_articles_controller.rb

TP #8388
https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx?acid=5D6AC326B4D272C23E446C28586BAF51#page=board/5624876525867731357&appConfig=eyJhY2lkIjoiREI4ODcwRjkxMDNDRTM2NTlBMzhDNTRBRTVBNUU1N0UifQ==&searchPopup=Bug/8388
Summary
add new relic_ignore_enduser call to amp_articles_controller to prevent new relic js script being injected into AMP pages
Testing
Tested on UAT

add newrelic_ignore_enduser to amp articles controller

---

Gemfile
Gemfile.lock
README.md
app/controllers/admin/dashboard_controller.rb
bin/setup
config/database.yml
config/database.yml.postgres

- This PR fixes a PG Syntax error that was missed when running rspec tests locally, 
the test script was previously set to run using sqlite3 locally and syntax error not applicable when using mysql/sqlite3.
- update gems including http 0.5.0 > 3.0.0 to fix security vulnerability
- remove obsolete heroku config from app setup script

Fix postgresql syntax error, gem security vulnerabilities and remove legacy tech debt

---

app/controllers/admin/users_controller.rb

The login column is now encrypted. Use ID column instead to order in Manage Users.

[DEV APPROVED] Order users by id instead of login

---

app/controllers/admin/dashboard_controller.rb

Publify request on dashboard was taking a long time to respond or when is
fast was returning 404.
This request is not needed for the app so removing making everything responds
quick.

Remove publify requests

---

config/routes.rb

`ckeditor` tries to access a path helper relying on the fact that the engine's prefix name will always be respected and be equal to `ckeditor` when mounted into the host app.
When mounting inside a namespace, Rails will actually prepend the namespace to the route's prefix.
This PR moves the mounted route outside of the `admin` (Rails') "namespace".
BTW, an engine should not rely on something defined for the host app only (the mount point).
Please refer to this commit and comment: https://github.com/galetahub/ckeditor/commit/de6167a38394174d5c2e4543da804c3675c121dd#commitcomment-14412106

[DEV APPROVED] Fix ckeditor path helper usage from the host app
