app/assets/javascripts/ckeditor/config.js.erb, app/assets/stylesheets/administration_structure.css.scss, app/assets/stylesheets/ckeditor/editor.css, app/views/admin/content/_form.html.erb, lib/publify_textfilter_inline_callout.rb, lib/publify_textfilter_ma_says.rb, public/assets/ckeditor/editor.css
- Alter snippet code so that the markup which goes into the
editor is valid XHTML markup (HR tag)
- changed snippet example in admin accordingly
=> Alter snippet code

app/helpers/xml_helper.rb
Fix sitemap exception when looking for published and updated articles.
=> Fix the retrieval of published and updated articles

app/views/layouts/accounts.html.erb, app/views/layouts/administration.html.erb, app/views/layouts/default.html.erb, app/views/layouts/editor.html.erb, public/code.txt
- I was finding that the favicon wasn't working on articles
because it was referencing something in the 'current directory'
which was causing a 404
- Added name of blog as application name for Windows 8
=> Reference root in path to icons

app/assets/stylesheets/layouts/_footer.scss, app/views/shared/_footer.html.erb
PR to update the footer contact information, sitemap link and add the social links. CSS needs some serious review here, also I'm not sure how to handle the responsiveness of the icons. @benbarnett @Guntrisoft help :)
=> Footer stuff

app/assets/stylesheets/components/tiles/_article_tile.scss
Hopefully fixes IE9 tile grid issue
=> Removes overflow hidden for tiles

app/views/shared/_footer.html.erb
=> Update popular posts

app/views/shared/_campaign_link_article.html.erb, app/views/shared/_campaign_link_masays.html.erb, app/views/shared/_campaigns.html.erb
- extracted template code into partials and correctly
detect which type of link to output the link as per
design
=> Campaign - detect and output correct link type

app/assets/images/ma-says.svg, app/assets/stylesheets/_settings.scss, app/assets/stylesheets/components/article_body/_inline_callout.scss, app/assets/stylesheets/components/ma-says/_ma-says.scss, app/assets/stylesheets/layouts/_campaigns.scss, app/assets/stylesheets/layouts/_footer.scss, app/assets/stylesheets/layouts/_header.scss, app/assets/stylesheets/layouts/_tiles.scss, public/assets/ma-says.svg
- added width/height to ma says svg to ensure it renders correctly
- added background-size aswell to ensure ma says renders correctly
- create a fallback font family for museo_slab
- re done the inline callout stripy background, and make sure it
works across browsers
- ensure the height of the social buttons is specified
- ensure title on homepage is centered
- re-worked tiles on homepage to ensure they work across browsers
=> fixing IE issues

app/views/shared/_sharing_buttons.html.erb
=> fix pinterest link

app/assets/stylesheets/layouts/_index.scss, app/views/articles/index.html.erb
- detect whether there is a campaign or not
so that we can render the index grey background
correctly
=> fix header rendering issues on homepage

app/assets/stylesheets/components/results_list/_results_list.scss, app/assets/stylesheets/layouts/_header.scss, app/controllers/articles_controller.rb, app/views/articles/archives.html.erb, app/views/articles/search.html.erb, app/views/shared/_header.html.erb, config/locales/en.yml, spec/controllers/articles_controller_spec.rb
- re-enabled the search magnify button in top right
- adjusted padding in header to match main MAS site
as per request by Jade
- modified search results page to include
search box and format search results to match
archive page
=> Adding search to the blog

app/assets/stylesheets/_settings.scss, app/assets/stylesheets/components/tiles/_article_tile.scss, app/assets/stylesheets/lib/_colors.scss, app/helpers/article_helper.rb, app/models/tag.rb, app/views/articles/_popular_tags.html.erb, app/views/articles/index.html.erb, app/views/shared/_article_tile.html.erb
- added it to the tag matrix as 3rd tile
=> adding popular tags tile

app/views/articles/archives.html.erb, app/views/articles/search.html.erb, config/locales/en.yml
- added to search and archive templates
=> adding hidden text to say 'published by'

app/assets/stylesheets/_settings.scss, app/assets/stylesheets/components/campaigns-link/campaigns-link.scss, app/assets/stylesheets/components/comments/_comments.scss, app/assets/stylesheets/components/tiles/_article_tile.scss, app/assets/stylesheets/lib/_colors.scss, app/views/articles/_comment_form.html.erb, app/views/articles/read.html.erb, app/views/comments/_comment.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_header.html.erb, config/locales/en.yml
=> Tweaks from accessibility audit

app/assets/stylesheets/components/article_body/_article_body.scss
- added to any links which don't mention moneyadviceservice.org.uk
=> added external link icon

app/assets/stylesheets/components/skip_to_link/_all.scss, app/assets/stylesheets/components/skip_to_link/_skip_to_link.scss, app/views/articles/archives.html.erb, app/views/articles/index.html.erb, app/views/articles/read.html.erb, app/views/articles/search.html.erb, app/views/articles/view_page.html.erb, app/views/author/show.html.erb, app/views/shared/_header.html.erb, app/views/tags/show.html.erb
- added main tag with id="main" to all page layouts
- added styling for skip link so on focus it displays
in top left corner
=> skip to link for main and accessibility statement

app/assets/stylesheets/components/comments_count/_comments_count.scss
- bug was causing display issues on the search results and
archive pages
=> fixing bug in iOS 7.1.2

app/assets/stylesheets/components/ma-says/_ma-says.scss
- ma says module was appearing slightly larger than 100%
causing articles on mobile to horizontally scroll slightly
=> ma says module display issue on mobile

app/controllers/application_controller.rb, config/environments/production.rb
Just learnt of this from RAD...
=> Force ssl in production via the environment config instead of in the controller

config/environments/staging.rb
=> Dont enforce SSL in staging

config/unicorn.rb
As we are experiencing exceeding memory issues
=> reduce number of unicorns from 3 => 2

app/assets/stylesheets/layouts/_header.scss, app/views/shared/_campaigns.html.erb, app/views/shared/_header.html.erb, bin/setup
Make the header a little shorter, remove beta status, link to content. 
Story 6388
=> Blog header optimisation

Gemfile, app/controllers/xml_controller.rb, app/views/xml/_googlesitemap_item_article.googlesitemap.builder, app/views/xml/_googlesitemap_item_news.googlesitemap.builder, app/views/xml/news_feed.googlesitemap.builder, config/routes.rb, spec/requests/news_sitemap_spec.rb, spec/requests/sitemap_spec.rb
- Tweak existing sitemap to only return url to resources and remove other content
- Add news sitemap which returns only news articles within the last 48 hours. This contains specific content for google news
=> Xml sitemap

app/models/article.rb, app/views/articles/archives.html.erb, app/views/articles/search.html.erb, app/views/layouts/default.html.erb
on search and archive sections
=> add relation metadata for previous/next pages

Gemfile, Gemfile.lock, config/application.rb
- this redirects `/foo////////` to `/foo`
=> Handle trailing slashes

app/assets/stylesheets/layouts/_header.scss, app/assets/stylesheets/lib/_mixins.scss
Andy spotted that the blog header was a little misaligned after we removed the BETA icon. Just fixed that and cleaned up a few things.
=> Fix header text alignment bug

app/views/shared/_rss_item_article.rss.builder
- Add author to rss feed
- Also add hero image as an part of an enclosure on an article item
=> Tweak article rss

app/assets/stylesheets/layouts/_header.scss
Changing the styling of these links so that on hover they change
appearance to be underlined.
=> [DEV APPROVED] Adding underline to blog header link on hover

db/seeds.rb
Updating seed.db to include the tag "Survive January" for the upcoming campaign.  The tag has already been added to staging and signed off, and is also now on production.
=> [DEV APPROVED] Adding survive January tag

app/views/admin/content/_form.html.erb
Adding Brightcove video snippet, using same width + height as the default youtube video embed code to add consistency
=> [DEV APPROVED] Adding brightcove video snippet to blog

app/views/admin/content/_form.html.erb, app/views/shared/_footer.html.erb
Updating the phone number in the footer and the number of people who
have signed up from 200,000 to 270,000+
Phone number:
People count:
=> [DEV APPROVED] 7162 - Update phone number & people count

app/views/admin/content/_form.html.erb
The URL in this project is required when a cost calculator tool is embedded into a blog post
=> Replacing Rack CDN with Azure CDN

README.md
We are using an internal Continuous integration now
=> Remove codeship flag

build.sh
add asset container variable to build.sh script, this will pickup the env variable set on the Go pipeline for the application
=> [DEV APPROVED] add new ASSET_CONTAINER variable to build.sh for asset upload

Gemfile, Gemfile.lock, app/assets/javascripts/require_config.js.erb, app/assets/stylesheets/_enhanced.css.scss, app/assets/stylesheets/layouts/_footer.scss, app/assets/stylesheets/layouts/_header.scss, app/views/articles/search.html.erb, bower.json.erb, spec/models/note_spec.rb, spec/models/post_type_spec.rb, spec/models/redirect_spec.rb, spec/models/tag_spec.rb
Reverts moneyadviceservice/publify#201
Pulling in the latest version of dough has caused issues with viewing blog posts, this reverts the changes while investigation takes place
=> Revert "[DEV APPROVED] 7558 - Blog: Post search focus should remain on the search box"

Gemfile, Gemfile.lock, README.md
**Note**
Update note on how to install gem `eventmachine`
=> [DEV APPROVED] Update Readme for eventmachine :notebook:

app/assets/stylesheets/components/footer_secondary/_footer_secondary.scss, app/views/shared/_footer.html.erb, config/locales/en.yml
[TP 10170](https://moneyadviceservice.tpondemand.com/restui/board.aspx?#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiRkRBMzk3RTBGNjU3NDg1RDM4QzczMTJFNzI5MDFBN0MifQ==&boardPopup=userstory/10170/silent)
**Summary**
The website footer should include a copyright notice with the year, name and address of The Money Advice Service
=> [DEV APPROVED] Add copyright notice to the footer

bower.json.erb, config/database.yml
[TP 10467](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/5682182231901749200&appConfig=eyJhY2lkIjoiNTM0ODcyOThDQjBDMTMyMDgyMTBENEZEM0QwM0ZBQzkifQ==&boardPopup=userstory/10467/silent)
Changed the version of Yeast regarding updates to the footer colour.
=> [DEV APPROVED] 10467 new footer colour

bower.json.erb
[TP 10468](https://moneyadviceservice.tpondemand.com/RestUI/Board.aspx#page=board/5253959470622112123&appConfig=eyJhY2lkIjoiNTM0ODcyOThDQjBDMTMyMDgyMTBENEZEM0QwM0ZBQzkifQ==&boardPopup=userstory/10468/silent)
Bumped Yeast Version in Bower to reflect the latest style changes.
=> [DEV APPROVED] Bumped Yeast Version in Bower
